In [ ]:
import json
import csv
import tweepy
import re
from tweepy import streaming
from tweepy import StreamListener
import pandas as pd

In [ ]:
def search_for_hashtags(consumer_key, consumer_secret, access_token, access_token_secret, hashtag_phrase):
    
    #create an authorization for accessing Twitter (aka tell the program we have permission to do what we're doing)
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
  

    #initialize Tweepy API
    api = tweepy.API(auth)
    api =tweepy.API(auth,wait_on_rate_limit=True,wait_on_rate_limit_notify=True)

    
    #make the name of the spreadsheet we will write to
    #it will be named whatever we search
    fname = '_'.join(re.findall(r"#(\w+)", hashtag_phrase))

    #open the spreadsheet we will write to
    with open('%s.csv' % (fname), 'w', encoding='utf-8') as file:

        w = csv.writer(file)

        #write header row to spreadsheet
        w.writerow(['timestamp', 'tweet_text', 'username', 'all_hashtags', 'followers_count'])

        #for each tweet matching our hashtags, write relevant info to the spreadsheet
        #max we can pull is 500,000 tweets a month; I have it set to 100
        for tweet in tweepy.Cursor(api.search, q=hashtag_phrase+' -filter:retweets', 
                                   lang="en",  tweet_mode='extended').items(2000000):
            w.writerow([tweet.created_at, tweet.full_text.replace('\n',' ').encode('utf-8'), tweet.user.screen_name.encode('utf-8'), [e['text'] for e in tweet._json['entities']['hashtags']], tweet.user.followers_count])

In [ ]:
#this creates input boxes where you will input your keys given to you by twitter
consumer_key = input('Consumer Key ')
consumer_secret = input('Consumer Secret ')
access_token = input('Access Token ')
access_token_secret = input('Access Token Secret ')
    
hashtag_phrase = input('Hashtag Phrase ') #you'll enter your search terms in the form "#xyz" ; use logical operators AND/OR

if __name__ == '__main__':
    search_for_hashtags(consumer_key, consumer_secret, access_token, access_token_secret, hashtag_phrase)

In [ ]:
data = pd.read_csv('UkrainevsRussia.csv')

In [ ]:
data.head()

,timestamp,tweet_text,username,all_hashtags,followers_count
0,2022-05-21 16:42:50,b'The US government wants to seize $33 billion...,b'CrownFortunes',"['UkrainevsRussia', 'RussianAssets']",482
1,2022-05-20 21:17:51,"b'#UkraineVsRussia #UkraineWillWin - Okay, so ...",b'USAS_WW1',"['UkraineVsRussia', 'UkraineWillWin', 'SlavaUk...",9300
2,2022-05-20 13:16:01,"b'Russian, US military chiefs discuss Ukraine ...",b'roufaminnews5',"['Moscow', 'Russia', 'Ukraine', 'War', 'Russia...",5048
3,2022-05-17 13:49:10,"b'So, how does a geared-powered bike resemble ...",b'MyMzemo',"['EffectivelyRunBaselines', 'PurposefulLivesMa...",6996
4,2022-05-17 12:06:38,b'@BBCYaldaHakim @heatherbarr1 BREAKING NEWS :...,b'OfficialDNATV',"['BreakingNews', 'ukraine', 'UkraineUnderAttac...",131